language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t "$DOCKER_USER"/udagram-frontend:latest .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/udagram-frontend:latest